### ISSUE TITLE
검색 UI index page

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#102]
## What to make
![image](https://user-images.githubusercontent.com/60775453/133883042-e454517e-5af3-4f55-98c5-57951b797b46.png)

**Comment by hy57in** [comment]
@rmfpdlxmtidl  고민이 있는데요, 최근 검색어와 인기 검색어를 각각 컴포넌트로 만드는게 좋을까요? 아니면 다른곳에서 재사용되지 않으니 index 페이지에 한번에 만들까요?

**Comment by rmfpdlxmtidl** [comment]
우선 페이지에 넣고, 나중에 재사용할 때 컴포넌트로 분리하면 좋을 거 같아요. 이게 처음부터 컴포넌트로 분리하면 번거로운 점이 있더라구요
