### ISSUE TITLE
네이버 지도 Open API 인증 실패

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#114]
## Issue description
![image](https://user-images.githubusercontent.com/60775453/133921357-d7d4b4ab-8616-40c5-922c-5098368830e1.png)

## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
네이버 지도는 아래 URL로 접근해야만 표시됩니당

> http://localhost:3000 (로컬 개발 주소)
https://sobok-git-develop-teamsindy20.vercel.app (develop 브랜치 배포 주소)
https://sobok.vercel.app (main 브랜치 배포 주소)
