### ISSUE TITLE
매장상세페이지 -> 메뉴탭 -> 메뉴명 위 아이콘 깨짐

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#117]
## Issue description
![image](https://user-images.githubusercontent.com/60775453/133922030-bcb8a957-6b06-4523-88d5-d67026db8942.png)

## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
이슈가 중복됐네용
