### ISSUE TITLE
[Error] Minified React error #143

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#27]
## Issue description

![image](https://user-images.githubusercontent.com/60775453/131167654-232e4eda-df63-4b27-b221-dc2f3d32205e.png)
> BottomHeader를 만들고 이를 index에 붙일 때 발생한 문제
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #143; visit https://reactjs.org/docs/error-decoder.html?invariant=143 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
[Error Decoder](https://reactjs.org/docs/error-decoder.html?invariant=143) 에 들어갔더니
`In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.`
`React.Children.only expected to receive a single React element child.`
라고 나온다.

```tsx
HomePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <PageHead>
      <TopHeader>
        <BottomHeader>{page}</BottomHeader>
      </TopHeader>
    </PageHead>
  )
}
```

## Steps to reproduce the issue

1. feature/#23/bottom-navigation 에 체크아웃 한다
2. yarn build
3.

## What's the expected result?

정상 작동
## What's the actual result?

빌드 실패
## Additional details
https://reactjs.org/docs/error-decoder.html/?invariant=143

**Comment by rmfpdlxmtidl** [comment]
> React.Children.only expected to receive a single React element child.

> https://github.com/vercel/next.js/issues/1605#issuecomment-292130017

Link 컴포넌트 아래 1개 초과하는 자식 컴포넌트가 있었기 때문에 발생했어요.
