### ISSUE TITLE
svg 크기, 색 변경하기

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#29]
React Component 로 만드는건 어떤가요?
[참고](https://kyounghwan01.github.io/blog/React/handling-svg/#%E1%84%89%E1%85%A1%E1%84%8B%E1%85%AD%E1%86%BC%E1%84%87%E1%85%A5%E1%86%B8)

**Comment by rmfpdlxmtidl** [comment]
좋아요ㅎㅎ
