### ISSUE TITLE
stores/[id]/info 페이지 문의

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#61]
## Issue description

```
<div>
    <Link href={`/stores/${storeId}/info`}>정보</Link>{' '}
    <Link href={`/stores/${storeId}/news`}>소식</Link>{' '}
    <Link href={`/stores/${storeId}/feed`}>피드</Link>{' '}
    <Link href={`/stores/${storeId}/menus`}>메뉴</Link>{' '}
  </div>
```
여기서 `정보` 탭 링크 문의드립니다
![image](https://user-images.githubusercontent.com/60775453/132170501-d03f317f-bb98-4323-80d8-fbf5c6191f35.png)
![image](https://user-images.githubusercontent.com/60775453/132170690-015c70c3-2a50-4ea4-8713-5fcb213af4ec.png)
![image](https://user-images.githubusercontent.com/60775453/132170706-3a66b8e4-c2a1-4111-94c1-8f72336c63c0.png)

현재 info에 해당하는 페이지는 `stores/[id]/ (index)`에 해당하는걸로 하기로 했는데
혹시 info 페이지는 새로 만들어야하나요? 잘못만드신건지, 의도가 궁금합니다!

## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
이거 수정을 빼먹었어요..//

`/stores/${storeId}/info` -> `/stores/${storeId}`

변경할께요~

**Comment by hy57in** [comment]
> 이거 수정을 빼먹었어요..//
> 
> `/stores/${storeId}/info` -> `/stores/${storeId}`
> 
> 변경할께요~



> 이거 수정을 빼먹었어요..//
> 
> `/stores/${storeId}/info` -> `/stores/${storeId}`
> 
> 변경할께요~

넴!
