### ISSUE TITLE
[Error] Duplicate atom key "currentTown" 에러

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#62]
## Issue description
![image](https://user-images.githubusercontent.com/60775453/132295871-b6c4e1cd-431d-4dbe-9163-37f3d43bac34.png)

## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
`yarn dev` 중에 발생하는 거라면 무시해도 괜찮을 거 같아요. 만약 `yarn start`에서 발생하는 거라면 다시 열어주세요!
