### ISSUE TITLE
StoreNewsQuery에 store가 없음

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#73]
## Issue description

![image](https://user-images.githubusercontent.com/60775453/132393906-9e58eb9d-9c53-4f9c-a66c-9eea312fc3c0.png)
newscard 에 store.name을 사용하기 위해 필요한데 없음
## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
StoreNews는 `/stores/[id]/news` 페이지에서 사용하는 거라 매장 이름이 필요하지 않아요!

**Comment by hy57in** [comment]
> StoreNews는 `/stores/[id]/news` 페이지에서 사용하는 거라 매장 이름이 필요하지 않아요!
> 
> 반면 NewsList는 `/news/all` 또는 `/news` 페이지에서 사용하는 거라 매장 필드가 있어요 ㅎㅎ

아 맞네요! store엔 없어도 되는거 어제 알았어요 ㅋㅋㅋ
