### ISSUE TITLE
소식 카드에 매장 정보 조건부 렌더링하기

### ISSUE THREAD

**Issue by rmfpdlxmtidl** [teamsindy20/sobok#77]
### `/news/all` 페이지

![image](https://user-images.githubusercontent.com/33145190/132658932-d1e4a3e5-1122-4702-86ff-7708b5253917.png)

### 와이어 프레임

![image](https://user-images.githubusercontent.com/33145190/132659064-e4549bf2-8ff6-4954-b93e-e7b4d51c30d0.png)

`/news/all` 및 `/news` 페이지에 있는 소식 카드엔 매장 이름과 매장 이미지가 보여야 해요 ㅎㅎ

## Why is it necessary

와이어프레임과 디자인 일치시키기

## Additional Considerations

- 조건부 렌더링을 통해 `NewsCard` 컴포넌트의 `news` prop에 `store` 객체가 있으면 매장 정보를 보여주기

**Comment by hy57in** [comment]
헉 지웠는뎁ㅜㅜ 근데 그럼 NewsCard 컴포넌트 하나로 두개의 버전을 만드는건가요? 
아니면 StoreNewsCard를 새로 만드는 건가요?

**Comment by rmfpdlxmtidl** [comment]
백엔드 PR을 develop로 머지해야해요!!
