### ISSUE TITLE
하트 아이콘 깨짐 오류

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#96]
## Issue description
![7C7648D5-415A-4DD6-89ED-C5EA3F6B571E](https://user-images.githubusercontent.com/60775453/133414635-578c82ad-5469-45cc-903a-29b008532df6.jpeg)

피드 및 메뉴카드에서 하트 아이콘이 깨짐

## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
제가 svg 파일 지우고 컴포넌트화했는데 저기는 아직 손보지 않아서 그런 거 같아요 ㅎㅎ
