### ISSUE TITLE
[Error] client side exeption has occured

### ISSUE THREAD

**Issue by hy57in** [teamsindy20/sobok#98]
## Issue description
![2ECCBC23-271D-436B-8097-78F764A24AB0](https://user-images.githubusercontent.com/60775453/133415089-b54fab49-fe20-4aca-87e8-0011360d4dfd.png)

## Steps to reproduce the issue

1.
2.
3.

**Comment by rmfpdlxmtidl** [comment]
카카오 API 호출 관련 오류였어요
